# THIS FILE IS AUTOMATICALLY GENERATED. IT IS POINTLESS TO MODIFY IT

from setuptools import setup

try:
    with open('readme.rst') as f:
        long_description = f.read()
except FileNotFoundError:
    long_description = 'Configuration for python made easy' 

setup(
    name='pyconfiglib',
    version='1.2.4',
    packages=['configlib'],
    url='https://github.com/ddorn/pyconfiglib',
    license='MIT',
    author='Diego Dorn',
    author_email='diego.dorn@free.fr',
    description='Configuration for python made easy',
    long_description=long_description,
    install_requires=['click==6.*', 'pygments==2.*'],
    include_package_data=True,
    scripts=dict(console_scripts=[])
)
